---
- name: Add users
  user: 
      name: "{{ item.name }}"
      uid: "{{ item.uid }}"
      groups: "{{ item.groups }}"
      append: yes
      createhome: no
      state: present
  with_items: "{{unixusers}}"
